name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:   # required if we want to run it manually 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "triggered by ${{ github.event_name }}"
          echo "branch is ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0  # MW what is this?
      - name: list the files in the repo
        run: |
          echo "The repo ${{ github.repository }} contains the following files: "
          tree
  
